### ISSUE TITLE
(tcp-client) and (udp-client) cause "lein uberjar" to hang

### ISSUE THREAD

**Issue by honza** [aphyr/riemann-clojure-client#17]
If you add a top-level `(tcp-client {...})` call, `lein uberjar` will just sit there indefinitely.

**Comment by aphyr** [comment]
Why are you doing this? Generally you don't want to open network connections at compile time....
On Sep 29, 2015 11:24 AM, Honza Pokorny <notifications@github.com> wrote:If you add a top-level (tcp-client {...}) call, lein uberjar will just sit there indefinitely.

**Comment by honza** [comment]
I'm storing a reference to the client. `(def riemann (r/tcp-client))` per the documentation. Should I be connecting each time I want to send a metric?

**Comment by aphyr** [comment]
Wait, in riemann.config? Or in some other project? In riemann.config it's fine but if you're aot compiling you probably want some lifecycle management in place.
On Sep 29, 2015 14:00, Honza Pokorny <notifications@github.com> wrote:I'm storing a reference to the client. (def riemann (r/tcp-client)) per the documentation. Should I be connecting each time I want to send a metric?

**Comment by honza** [comment]
> you probably want some lifecycle management in place

Yes, that might be a good idea.

I expected the `tcp-client` call to work like other similar things. For example, jdbc or carmine. It seems to connect lazily compared to the riemann client. I can't figure from the output of `lein uberjar` what it's doing. Adding print statements around the `(tcp-client)` call makes it sound like it connects just fine but then the ns compilation still hangs.

I guess I'll finally have to learn how to use stuartsierra/component.

**Comment by honza** [comment]
TIL that jdbc actually opens a new connection each time you call `execute!`.
